(function(){
 const PDF_URL='assets/book.pdf';
 const $=id=>document.getElementById(id);
 const canvas=$('pdfCanvas'), ctx=canvas.getContext('2d');
 let pdf=null, page=1, zoom=1, rendering=false, pending=null;
 if(window.pdfjsLib) pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
 function buildToc(){const list=$('tocList');let group='';(window.BOOK_CONTENTS||[]).forEach(item=>{if(item.group!==group){group=item.group;const h=document.createElement('div');h.className='toc-group';h.textContent=group;list.appendChild(h)}const a=document.createElement('a');a.className='toc-link';a.href='#page='+item.page;a.dataset.page=item.page;const t=document.createElement('span');t.className='toc-title';t.textContent=item.title;const p=document.createElement('span');p.className='toc-page';p.textContent=item.page;a.append(t,p);a.addEventListener('click',e=>{e.preventDefault();goTo(Number(item.page));if(innerWidth<900)$('sidebar').classList.remove('open')});list.appendChild(a)});}
 function update(){ $('pageNum').value=page;$('bottomPage').value=page;$('zoomLabel').textContent=Math.round(zoom*100)+'%';document.querySelectorAll('.toc-link').forEach(a=>a.classList.toggle('active',Number(a.dataset.page)===page));$('prevBtn').disabled=$('bottomPrev').disabled=page<=1;$('nextBtn').disabled=$('bottomNext').disabled=page>=pdf.numPages; }
 async function renderPage(num){if(!pdf)return;if(rendering){pending=num;return}rendering=true;$('loading').classList.remove('hidden');try{const p=await pdf.getPage(num);const stage=$('stage');const maxWidth=Math.max(250,stage.clientWidth-54);const base=p.getViewport({scale:1});const fitScale=Math.min(maxWidth/base.width,1.55);const scale=fitScale*zoom;const viewport=p.getViewport({scale});const dpr=window.devicePixelRatio||1;canvas.width=Math.floor(viewport.width*dpr);canvas.height=Math.floor(viewport.height*dpr);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,viewport.width,viewport.height);await p.render({canvasContext:ctx,viewport}).promise;page=num;update();}catch(e){console.error(e)}finally{$('loading').classList.add('hidden');rendering=false;if(pending){const n=pending;pending=null;renderPage(n)}}}
 function goTo(n){if(!pdf)return;page=Math.max(1,Math.min(pdf.numPages,Math.floor(n)||1));renderPage(page);$('stage').scrollTop=0}
 function toggleSide(){ $('sidebar').classList.toggle('open'); }
 $('menuToggle').onclick=toggleSide;$('contentsBtn').onclick=toggleSide;$('bottomContents').onclick=toggleSide;$('closeSidebar').onclick=()=> $('sidebar').classList.remove('open');
 $('prevBtn').onclick=$('bottomPrev').onclick=()=>goTo(page-1);$('nextBtn').onclick=$('bottomNext').onclick=()=>goTo(page+1);
 function inputPage(el){el.addEventListener('change',()=>goTo(el.value));el.addEventListener('keydown',e=>{if(e.key==='Enter')goTo(el.value)})}inputPage($('pageNum'));inputPage($('bottomPage'));
 $('zoomIn').onclick=()=>{zoom=Math.min(2.5,zoom+.1);renderPage(page)};$('zoomOut').onclick=()=>{zoom=Math.max(.5,zoom-.1);renderPage(page)};$('fitBtn').onclick=()=>{zoom=1;renderPage(page)};
 function full(){if(!document.fullscreenElement){document.documentElement.requestFullscreen?.()}else document.exitFullscreen?.()}$('fullBtn').onclick=$('bottomFull').onclick=full;
 $('searchInput').addEventListener('input',e=>{const q=e.target.value.toLocaleLowerCase();document.querySelectorAll('.toc-link').forEach(a=>a.classList.toggle('hidden',q&&!a.querySelector('.toc-title').textContent.toLocaleLowerCase().includes(q)));document.querySelectorAll('.toc-group').forEach(g=>{let n=g.nextElementSibling,any=false;while(n&& !n.classList.contains('toc-group')){if(n.classList.contains('toc-link')&&!n.classList.contains('hidden'))any=true;n=n.nextElementSibling}g.classList.toggle('hidden',!!q&&!any)})});
 document.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.key==='ArrowRight'||e.key==='PageDown')goTo(page+1);if(e.key==='ArrowLeft'||e.key==='PageUp')goTo(page-1);if(e.key==='+'||e.key==='='){zoom=Math.min(2.5,zoom+.1);renderPage(page)}if(e.key==='-'){zoom=Math.max(.5,zoom-.1);renderPage(page)}});
 window.addEventListener('resize',()=>renderPage(page));
 buildToc();pdfjsLib.getDocument(PDF_URL).promise.then(doc=>{pdf=doc;$('pageCount').textContent=$('bottomCount').textContent=doc.numPages;goTo(1)}).catch(err=>{$('loading').textContent='PDF файлы ашылмады. assets/book.pdf файлының бар екенін тексеріңіз.';console.error(err)});
})();
